@startuml Analise de requisitos

actor Analista
usecase Produtos
usecase Clientes
usecase Vendedores
usecase Pedidos

note top of Analista : Etapa 1: Análise de requisitos (realidade)
Analista --> Produtos
Analista --> Clientes
Analista --> Vendedores
Analista --> Pedidos

@enduml
