---
config: 
    theme: dark
    look: handDrawn
    title: Análise de requisitos (realidade)
---

flowchart TD
    actor@{shape: circle, label: "👤 Ator"}
    uc-produtos@{shape: rounded, label: "Produtos"}
    uc-clientes@{shape: rounded, label: "Clientes"}
    uc-vendedores@{shape: rounded, label: "Vendedores"}
    uc-pedidos@{shape: rounded, label: "Pedidos"}

    actor --> uc-produtos
    actor --> uc-clientes
    actor --> uc-vendedores
    actor --> uc-pedidos

    %% O mermaid não possui representações para diagramas de casos de uso.
    %% 'circle' simula o ator
    %% 'rounded' simula o caso de uso
    