---
config:
    title: Modelagem de dados conceitual (Visão do vendedor de varejo)
    theme: dark
    look: handDrawn
---

erDiagram 
    direction LR
    cliente
    produto
    vendedor

    cliente }o--o{ produto : pedidos
    cliente }o -- |{ vendedor : "atendido por"
    produto }o--o{ vendedor : "vendido por"

    "Visão do vendedor de varejo"