---
config:
    title: Transformação do modelo de dados conceitual em tabelas SQL
    theme: dark
    look: handDrawn
---

erDiagram 
    direction LR
    cliente {
        integer num_cli
        varchar nome_cli      
    }
    produto {
        integer num_produto
        varchar nome_prod
        interger qtd_estoque
    }
    vendedor {
        varchar nome_vendedor
        varchar endereco
        varchar dept
        varchar nivel_cargo
        integer dias_ferias
    }
    pedido {
        integer num_pedido
        varchar nome_vendedor
        integer num_cli
    }
    pedido_produto {
        integer num_pedido
        integer num_produto
    }

    %% exemplo de SQL usada para criação das tabelas do banco de dados %%
    "**Exemplo de código SQL** <br> create table cliente (num_cli integer, nome_cli varchar etc...)"

    cliente ||--o{ pedido : faz
    pedido }o--o{ produto : para
    cliente }o--|| vendedor : "atendido por"
    vendedor ||--o| pedido : preenche
    pedido_produto }o--o{ pedido : "associa pedido a produto"
    pedido_produto }o--o{ produto : "associa pedido a produto"